USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS MASTERCLASS
  COMMENT = 'Database for the Snowflake Masterclass'
  DATA_RETENTION_TIME_IN_DAYS = 5;

CREATE WAREHOUSE IF NOT EXISTS MASTERCLASSWH
  WAREHOUSE_TYPE = STANDARD 
  WAREHOUSE_SIZE = XSMALL
  MAX_CLUSTER_COUNT = 2
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = STANDARD
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Masterclass Warehouse'
  ENABLE_QUERY_ACCELERATION = TRUE 
  QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2;

USE ROLE SYSADMIN;
USE DATABASE MASTERCLASS;
USE SCHEMA PUBLIC;
USE WAREHOUSE MASTERCLASSWH;

CREATE FILE FORMAT IF NOT EXISTS MASTERCLASS.PUBLIC.PARQUET_FILE_FORMAT
 TYPE = PARQUET 
 COMPRESSION = SNAPPY
 USE_VECTORIZED_SCANNER = TRUE;

CREATE STAGE IF NOT EXISTS  MASTERCLASS.PUBLIC.DATA_STAGE_AZURE
 STORAGE_INTEGRATION = MASTERCLASS_AZURE
 URL = 'azure://<myaccount>.blob.core.windows.net/<container>/path1'
 COMMENT = 'Lineitems data stage Azure';
