USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE MASTERCLASS
  COMMENT = 'Database for the Snowflake Masterclass'
  DATA_RETENTION_TIME_IN_DAYS = 5;

CREATE OR REPLACE WAREHOUSE MASTERCLASSWH
  WAREHOUSE_TYPE = STANDARD 
  WAREHOUSE_SIZE = XSMALL
  MAX_CLUSTER_COUNT = 2
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = STANDARD
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Masterclass Warehouse'
  ENABLE_QUERY_ACCELERATION = TRUE 
  QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2;

USE ROLE SYSADMIN;
USE DATABASE MASTERCLASS;
USE SCHEMA PUBLIC;
USE WAREHOUSE MASTERCLASSWH;

CREATE OR REPLACE FILE FORMAT MASTERCLASS.PUBLIC.PARQUET_FILE_FORMAT 
 TYPE = PARQUET 
 COMPRESSION = SNAPPY
 USE_VECTORIZED_SCANNER = TRUE;

CREATE STAGE IF NOT EXISTS  MASTERCLASS.PUBLIC.DATA_STAGE
 URL='s3://<bucket>/lineitems/'
 STORAGE_INTEGRATION = MASTERCLASS
 COMMENT = 'Lineitems data stage';
