USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION MASTERCLASS
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<iam_role>' -- Terraform output
  STORAGE_ALLOWED_LOCATIONS = ('<protocol>://<bucket>/<path>/') -- Terraform output

DESC INTEGRATION MASTERCLASS;
