USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION MASTERCLASS
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<iam_role>' -- Terraform output
  STORAGE_ALLOWED_LOCATIONS = ('<protocol>://<bucket>/<path>/') -- Terraform output

DESC INTEGRATION MASTERCLASS;

-- Get and substitute in terraform
-- STORAGE_AWS_IAM_USER_ARN -> Principal->AWS
-- STORAGE_AWS_EXTERNAL_ID -> sts:ExternalId

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION MASTERCLASS TO ROLE SYSADMIN;