USE DATABASE MASTERCLASS;
USE SCHEMA PUBLIC;
USE WAREHOUSE MASTERCLASSWH;

CREATE FILE FORMAT IF NOT EXISTS JSON_FILE_FORMAT
 TYPE = 'JSON'
 ENABLE_OCTAL = FALSE
 ALLOW_DUPLICATE  = TRUE
 STRIP_OUTER_ARRAY = TRUE
 STRIP_NULL_VALUES = TRUE
 IGNORE_UTF8_ERRORS = FALSE;

-- Uploading file to S3
-- aws s3 cp usedCars.json s3://masterclass-demo-desired-marten/demo/

-- Creating stage to read the file from S3
CREATE STAGE IF NOT EXISTS  MASTERCLASS.PUBLIC.DEMO_STAGE
 URL='s3://<bucket>/lineitems/'
 STORAGE_INTEGRATION = MASTERCLASS
 COMMENT = 'Lineitems data stage';
