services:
  terraform:
    image: hashicorp/terraform:1.8
    volumes:
      - .:/infra
      - ~/.ssh:/root/.ssh
      - ~/.terraform.d/credentials.tfrc.json:/root/.terraform.d/credentials.tfrc.json
    working_dir: /infra
    environment:
      - ARM_CLIENT_ID=${ARM_CLIENT_ID}
      - ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}
      - ARM_TENANT_ID=${ARM_TENANT_ID}
      - ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}
