services:
  terraform:
    image: hashicorp/terraform:1.8
    volumes:
      - .:/infra
      - ~/.ssh:/root/.ssh
      - ~/.terraform.d/credentials.tfrc.json:/root/.terraform.d/credentials.tfrc.json
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
