USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MASTERCLASSWH;
USE SCHEMA MASTERCLASS.PUBLIC;

-- CREATE TABLE
CREATE OR REPLACE TABLE MASTERCLASS.PUBLIC.RAW_LINEITEMS_WAREHOUSE (
    PK_ID               NUMBER(38, 0) NOT NULL IDENTITY(1,1) COMMENT 'Primary key',
    V                   VARIANT COMMENT 'This is the JSON data from the file',
    FILE_NAME           VARCHAR(500) COMMENT 'This is the name of the file that was loaded into S3 bucket',
    FILE_LAST_MODIFIED  TIMESTAMP_NTZ COMMENT 'This is when the file was loaded into S3 bucket',
    INSERTED_DATE       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() COMMENT 'This is when the record was inserted into the table',
    CONSTRAINT RAW_LINEITEMS_PK PRIMARY KEY (PK_ID)
) COMMENT = 'LINEITEMS table to load the data from S3 bucket';

SHOW STAGES;

-- SELECT 5 VALUES
SELECT 
     t.$1 AS V
    ,METADATA$FILENAME AS FILE_NAME
    ,METADATA$FILE_LAST_MODIFIED AS FILE_LAST_MODIFIED
FROM @MASTERCLASS.PUBLIC.DATA_STAGE (file_format => PARQUET_FILE_FORMAT) t
LIMIT 5;

-- COPY ALL DATA
COPY INTO MASTERCLASS.PUBLIC.RAW_LINEITEMS_WAREHOUSE (V, FILE_NAME, FILE_LAST_MODIFIED)
FROM (
	SELECT 
		 t.$1 AS V
		,METADATA$FILENAME AS FILE_NAME
		,METADATA$FILE_LAST_MODIFIED AS FILE_LAST_MODIFIED
	FROM @MASTERCLASS.PUBLIC.DATA_STAGE (file_format => PARQUET_FILE_FORMAT) t
);

-- Counting 59,986,052
SELECT COUNT(*) FROM MASTERCLASS.PUBLIC.RAW_LINEITEMS_WAREHOUSE;

-- Select 5 random records
SELECT NULLIF(V:"L_ORDERKEY"::VARCHAR, '')      AS L_ORDERKEY
     , NULLIF(V:"L_PARTKEY"::VARCHAR, '')       AS L_PARTKEY
     , NULLIF(V:"L_SUPPKEY"::VARCHAR, '')       AS L_SUPPKEY
     , NULLIF(V:"L_LINENUMBER"::VARCHAR, '')    AS L_LINENUMBER
     , NULLIF(V:"L_QUANTITY"::VARCHAR, '')      AS L_QUANTITY
     , NULLIF(V:"L_EXTENDEDPRICE"::VARCHAR, '') AS L_EXTENDEDPRICE
     , NULLIF(V:"L_DISCOUNT"::VARCHAR, '')      AS L_DISCOUNT
     , NULLIF(V:"L_TAX"::VARCHAR, '')           AS L_TAX
     , NULLIF(V:"L_RETURNFLAG"::VARCHAR, '')    AS L_RETURNFLAG
     , NULLIF(V:"L_LINESTATUS"::VARCHAR, '')    AS L_LINESTATUS
     , NULLIF(V:"L_SHIPDATE"::VARCHAR, '')      AS L_SHIPDATE
     , NULLIF(V:"L_COMMITDATE"::VARCHAR, '')    AS L_COMMITDATE
     , NULLIF(V:"L_RECEIPTDATE"::VARCHAR, '')   AS L_RECEIPTDATE
     , NULLIF(V:"L_SHIPINSTRUCT"::VARCHAR, '')  AS L_SHIPINSTRUCT
     , NULLIF(V:"L_SHIPMODE"::VARCHAR, '')      AS L_SHIPMODE
     , NULLIF(V:"L_COMMENT"::VARCHAR, '')       AS L_COMMENT
FROM MASTERCLASS.PUBLIC.RAW_LINEITEMS_WAREHOUSE
ORDER BY RANDOM()
LIMIT 5;

-- QUERY RECORDS
SELECT NULLIF(V:"L_ORDERKEY"::VARCHAR, '')      AS L_ORDERKEY
     , NULLIF(V:"L_PARTKEY"::VARCHAR, '')       AS L_PARTKEY
     , NULLIF(V:"L_SUPPKEY"::VARCHAR, '')       AS L_SUPPKEY
     , NULLIF(V:"L_LINENUMBER"::VARCHAR, '')    AS L_LINENUMBER
     , NULLIF(V:"L_QUANTITY"::VARCHAR, '')      AS L_QUANTITY
     , NULLIF(V:"L_EXTENDEDPRICE"::VARCHAR, '') AS L_EXTENDEDPRICE
     , NULLIF(V:"L_DISCOUNT"::VARCHAR, '')      AS L_DISCOUNT
     , NULLIF(V:"L_TAX"::VARCHAR, '')           AS L_TAX
     , NULLIF(V:"L_RETURNFLAG"::VARCHAR, '')    AS L_RETURNFLAG
     , NULLIF(V:"L_LINESTATUS"::VARCHAR, '')    AS L_LINESTATUS
     , NULLIF(V:"L_SHIPDATE"::VARCHAR, '')      AS L_SHIPDATE
     , NULLIF(V:"L_COMMITDATE"::VARCHAR, '')    AS L_COMMITDATE
     , NULLIF(V:"L_RECEIPTDATE"::VARCHAR, '')   AS L_RECEIPTDATE
     , NULLIF(V:"L_SHIPINSTRUCT"::VARCHAR, '')  AS L_SHIPINSTRUCT
     , NULLIF(V:"L_SHIPMODE"::VARCHAR, '')      AS L_SHIPMODE
     , NULLIF(V:"L_COMMENT"::VARCHAR, '')       AS L_COMMENT
FROM MASTERCLASS.PUBLIC.RAW_LINEITEMS_WAREHOUSE
WHERE L_ORDERKEY IN (
'30370724',
'43675749',
'46386755',
'39896960',
'51780611'
);

ALTER WAREHOUSE IF EXISTS MASTERCLASSWH SUSPEND; -- Run again the previous query, the warehouse is not used.

---***************************** Processing *****************************---

CREATE OR REPLACE TABLE MASTERCLASS.PUBLIC.LINEITEMS_WAREHOUSE AS
SELECT NULLIF(V:"L_ORDERKEY"::VARCHAR, '')::VARCHAR(15)     AS L_ORDERKEY
     , NULLIF(V:"L_PARTKEY"::VARCHAR, '')::VARCHAR(15)      AS L_PARTKEY
     , NULLIF(V:"L_SUPPKEY"::VARCHAR, '')::VARCHAR(15)      AS L_SUPPKEY
     , NULLIF(V:"L_LINENUMBER"::VARCHAR, '')::INT           AS L_LINENUMBER
     , NULLIF(V:"L_QUANTITY"::VARCHAR, '')::FLOAT           AS L_QUANTITY
     , NULLIF(V:"L_EXTENDEDPRICE"::VARCHAR, '')::FLOAT      AS L_EXTENDEDPRICE
     , NULLIF(V:"L_DISCOUNT"::VARCHAR, '')::FLOAT           AS L_DISCOUNT
     , NULLIF(V:"L_TAX"::VARCHAR, '')::FLOAT                AS L_TAX
     , NULLIF(V:"L_RETURNFLAG"::VARCHAR, '')::VARCHAR(30)   AS L_RETURNFLAG
     , NULLIF(V:"L_LINESTATUS"::VARCHAR, '')::VARCHAR(30)   AS L_LINESTATUS
     , NULLIF(V:"L_SHIPDATE"::VARCHAR, '')::DATE            AS L_SHIPDATE
     , NULLIF(V:"L_COMMITDATE"::VARCHAR, '')::DATE          AS L_COMMITDATE
     , NULLIF(V:"L_RECEIPTDATE"::VARCHAR, '')::DATE         AS L_RECEIPTDATE
     , NULLIF(V:"L_SHIPINSTRUCT"::VARCHAR, '')::VARCHAR(30) AS L_SHIPINSTRUCT
     , NULLIF(V:"L_SHIPMODE"::VARCHAR, '')::VARCHAR(30)     AS L_SHIPMODE
     , NULLIF(V:"L_COMMENT"::VARCHAR, '')::VARCHAR(100)     AS L_COMMENT
FROM MASTERCLASS.PUBLIC.RAW_LINEITEMS_WAREHOUSE;

SELECT * FROM MASTERCLASS.PUBLIC.LINEITEMS_WAREHOUSE;
