USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS MASTERCLASS
  COMMENT = 'Database for the Snowflake Masterclass'
  DATA_RETENTION_TIME_IN_DAYS = 2;

CREATE OR REPLACE WAREHOUSE MASTERCLASSWH
  WAREHOUSE_TYPE = STANDARD
  RESOURCE_CONSTRAINT = 'STANDARD_GEN_2'
  WAREHOUSE_SIZE = SMALL
  MAX_CLUSTER_COUNT = 2
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = STANDARD
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Masterclass Warehouse'
  ENABLE_QUERY_ACCELERATION = TRUE
  QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2;

USE ROLE SYSADMIN;
USE DATABASE MASTERCLASS;
USE SCHEMA PUBLIC;
USE WAREHOUSE MASTERCLASSWH;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FILE_FORMAT
 TYPE = PARQUET 
 COMPRESSION = SNAPPY
 USE_VECTORIZED_SCANNER = TRUE;

CREATE STAGE IF NOT EXISTS DATA_STAGE
 URL='s3://<bucket>/lineitems/'
 STORAGE_INTEGRATION = MASTERCLASS
 COMMENT = 'Lineitems data stage';

CREATE STAGE IF NOT EXISTS DEMO_STAGE
 URL='s3://<bucket>/demo/'
 STORAGE_INTEGRATION = MASTERCLASS
 COMMENT = 'Demo stage';

CREATE STAGE IF NOT EXISTS DATAENG_STAGE
 URL='s3://<bucket>/dataeng/'
 STORAGE_INTEGRATION = MASTERCLASS
 COMMENT = 'Data Engineering stage';

COPY INTO 's3://<bucket>/lineitems/'
FROM (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM
)
STORAGE_INTEGRATION = MASTERCLASS
FILE_FORMAT = MASTERCLASS.PUBLIC.PARQUET_FILE_FORMAT
HEADER = TRUE 
MAX_FILE_SIZE = 8388608;

LIST @MASTERCLASS.PUBLIC.DATA_STAGE;
