USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE API INTEGRATION MASTERCLASS_GIT_INTEGRATION
    API_PROVIDER = GIT_HTTPS_API
    API_ALLOWED_PREFIXES = ('https://github.com/domfp13')
    ENABLED = TRUE
    ALLOWED_AUTHENTICATION_SECRETS = ALL
    COMMENT='Masterclass Git Repository';

GRANT USAGE ON INTEGRATION MASTERCLASS_GIT_INTEGRATION TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
USE DATABASE MASTERCLASS;
USE SCHEMA PUBLIC;
CREATE OR REPLACE GIT REPOSITORY snowflake_extensions
  API_INTEGRATION = MASTERCLASS_GIT_INTEGRATION
  ORIGIN = 'https://github.com/domfp13/masterclass.git';
