USE ROLE SYSADMIN;
CREATE DATABASE ACCOUNTADMIN_MGMT
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'ACCOUNTADMIN ADMIN DATABASE';

USE ROLE SYSADMIN;
USE DATABASE ACCOUNTADMIN_MGMT;

CREATE SCHEMA POLICIES
  WITH MANAGED ACCESS
  COMMENT = 'Administration purpose: User SAML MFA polcies, DO NOT DELETE.';

USE ROLE ACCOUNTADMIN;
USE DATABASE ACCOUNTADMIN_MGMT;
USE SCHEMA POLICIES;

CREATE OR REPLACE AUTHENTICATION POLICY LEGACY_SERVICE_ACCOUNTS_POLICY
  AUTHENTICATION_METHODS = ('ALL')
  MFA_ENROLLMENT = OPTIONAL
  CLIENT_TYPES = ('ALL')
  COMMENT = 'This policy is for all service accounts in the account';

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS ANALYST COMMENT = 'Read ALL ONLY access';
GRANT ROLE ANALYST TO ROLE SYSADMIN;

USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS YOURSERVICEACCOUNT
    LOGIN_NAME = 'YOURSERVICEACCOUNT'
	PASSWORD = 'YOUR_PASSWORD'
    DISPLAY_NAME = 'Service Account'
    FIRST_NAME = 'Service Account'
    LAST_NAME = 'Service Account'
    COMMENT = 'Service Account'
    DEFAULT_ROLE = ANALYST
    DEFAULT_NAMESPACE = MASTERCLASS
    DEFAULT_WAREHOUSE = MASTERCLASSWH
    MUST_CHANGE_PASSWORD = FALSE
	TYPE = LEGACY_SERVICE;

USE ROLE SECURITYADMIN;
GRANT ROLE ANALYST TO USER A226300;
GRANT USAGE ON DATABASE MASTERCLASS TO ROLE ANALYST;
GRANT USAGE ON SCHEMA MASTERCLASS.PUBLIC TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE MASTERCLASSWH TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MASTERCLASS.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MASTERCLASS.PUBLIC TO ROLE ANALYST;

USE ROLE ACCOUNTADMIN;
USE DATABASE ACCOUNTADMIN_MGMT;
USE SCHEMA POLICIES;
ALTER USER A226300 SET AUTHENTICATION POLICY LEGACY_SERVICE_ACCOUNTS_POLICY;